services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: always
  api:
    build:
      context: backend
    volumes:
      - ./backend:/api
    ports:
      - 8001:8001
    environment:
      DB_HOST: "database"
      RUN_MIGRATIONS_ON_STARTUP: "true"
      VIRTUAL_ENV: /venv