# generated by datamodel-codegen:
#   filename:  temp.json
#   timestamp: 2022-09-17T13:15:24+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Source(BaseModel):
    type: str
    id: str


class Metadata(BaseModel):
    primary: bool
    source: Source
    sourcePrimary: bool


class Name(BaseModel):
    metadata: Metadata
    displayName: str
    familyName: str
    givenName: str
    displayNameLastFirst: str
    unstructuredName: str


class Source1(BaseModel):
    type: str
    id: str


class Metadata1(BaseModel):
    primary: bool
    verified: bool
    source: Source1
    sourcePrimary: bool


class EmailAddress(BaseModel):
    metadata: Metadata1
    value: str


class GoogleProfileResponse(BaseModel):
    resourceName: str
    etag: str
    names: List[Name]
    emailAddresses: List[EmailAddress]
