{
 "title": "API ECS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_cpu_utilized_average{})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_memory_utilized_average{})"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_running_task_count_average{})"
    }
   ]
  },
  {
   "title": "Inbound Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_network_rx_bytes_average{})"
    }
   ]
  },
  {
   "title": "Outgoing Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_network_rx_bytes_average{})"
    }
   ]
  },
  {
   "title": "Storage Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_storage_read_bytes_average{})"
    }
   ]
  },
  {
   "title": "Storage Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(aws_ecs_containerinsights_storage_write_bytes_average{})"
    }
   ]
  }
 ]
}