{
 "title": "EC2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aws_ec2_cpuutilization_average{}"
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aws_ec2_cpucredit_usage_average{}"
    },
    {
     "expr": "aws_ec2_cpucredit_balance_average{}"
    }
   ]
  },
  {
   "title": "Incoming Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "aws_ec2_network_in_average{}" }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "aws_ec2_network_out_average{}" }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "aws_ec2_disk_read_bytes_average{}"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "aws_ec2_disk_write_bytes_average{}"
    }
   ]
  },
  {
   "title": "Status Check Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "aws_ec2_status_check_failed_average{}"
    }
   ]
  }
 ]
}