name: Run E2E tests
description: "Runs end-to-end tests against a live deployment"
inputs:
  environment:
    description: 'The environment to run e2e tests against.'
    required: true
  aws-access-key-id:
    description: 'The AWS access key ID to use.'
    required: true
  aws-secret-access-key:
    description: 'The AWS secret access key to use.'
    required: true
  staging-subdomain:
    description: 'The subdomain to use for staging deploys.'
    required: true
    default: staging
  e2e-rapid-api-key:
    description: 'The Rapid API key to use.'
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pipenv
    - name: Install Pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      shell: bash
      run: |
        cd ./e2e
        pipenv sync
        pipenv run playwright install
    - name: Run e2e tests
      shell: bash
      run: |
        cd ./infra/${{ inputs.environment }}
        ./scripts/e2e-test.sh
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        APP_STAGING_NAME_SUFFIX: ${{ inputs.staging-subdomain }}
        E2E_RAPID_API_KEY: ${{ inputs.e2e-rapid-api-key }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: e2e/test-results
