name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Github Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
